"""partial unique index for active crawl_queue per user

Revision ID: 280e2fd3e79f
Revises: 611554eed020
Create Date: 2026-08-01 22:16:54.106595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280e2fd3e79f'
down_revision: Union[str, Sequence[str], None] = '611554eed020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_crawl_queue_active_user', 'crawl_queue', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_crawl_queue_active_user', table_name='crawl_queue', postgresql_where=sa.text("status IN ('pending', 'processing')"))
    # ### end Alembic commands ###
