from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.config import settings

# Without this, Postgres auto-names constraints (or SQLAlchemy emits `None`
# and lets the DB pick), which means Alembic's autogenerated downgrade()
# has no name to reference when dropping them later — that's exactly what
# broke the discovered_by FK's downgrade. This convention makes every
# constraint name deterministic and derivable from the table/column, so
# future autogenerated migrations get real names on both upgrade AND
# downgrade automatically.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    insta_id: Mapped[int | None] = mapped_column(BigInteger, unique=True, nullable=True)
    username: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    name: Mapped[str | None] = mapped_column(Text, nullable=True)
    follower_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    following_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    profile_pic: Mapped[str | None] = mapped_column(Text, nullable=True)
    category: Mapped[str | None] = mapped_column(Text, nullable=True)
    country: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_seed: Mapped[bool] = mapped_column(Boolean, default=False)
    seed_association_score: Mapped[float] = mapped_column(Float, default=0.0)
    discovery_score: Mapped[int] = mapped_column(Integer, default=0)
    crawl_state: Mapped[str] = mapped_column(String, default="never_crawled")
    # 'never_crawled'          — eligible, follower_count known, not yet queued/crawled
    # 'queued'                 — sitting in crawl_queue
    # 'completed'               — following-list crawl finished
    # 'skipped_below_threshold' — known follower_count, doesn't clear the bar
    # 'enrichment_failed'      — follower_count UNKNOWN (HypeAuditor lookup
    #                            failed, not that we checked and it's low).
    #                            Can't be queued for the same reason
    #                            skipped_below_threshold can't — no valid
    #                            basis to justify a crawl. Retried on every
    #                            later re-discovery (app/graph_consumer.py)
    #                            and by scripts/retry_failed_enrichment.py
    #                            for accounts never re-discovered. On a
    #                            successful retry this resets back to
    #                            'never_crawled', not some third state.
    is_verified: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    is_private: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    discovered_by: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("users.id"), nullable=True
    )  # user_id of whoever's following-list first surfaced this account; NULL for seed rows
    last_crawled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    crawl_count: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=lambda: datetime.now(timezone.utc)
    )


class Edge(Base):
    __tablename__ = "edges"

    from_user_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("users.id"), primary_key=True)
    to_user_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("users.id"), primary_key=True)
    state: Mapped[str] = mapped_column(String, default="confirmed")
    discovered_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class CrawlQueue(Base):
    __tablename__ = "crawl_queue"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("users.id"))
    priority: Mapped[float] = mapped_column(Float, default=0.0)
    source_type: Mapped[str] = mapped_column(String)
    queue_type: Mapped[str] = mapped_column(String)
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    status: Mapped[str] = mapped_column(String, default="pending")
    available_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    locked_by: Mapped[str | None] = mapped_column(String, nullable=True)
    locked_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    last_crawl_duration: Mapped[float | None] = mapped_column(Float, nullable=True)

    __table_args__ = (
        # user_id is NOT unique/PK on purpose — a user can have multiple
        # historical rows (completed initial crawl, later a "refresh" job,
        # etc). What we actually want enforced is "at most one *active*
        # row per user at a time," which a partial index expresses and a
        # plain UNIQUE constraint can't.
        Index(
            "ux_crawl_queue_active_user",
            "user_id",
            unique=True,
            postgresql_where=text("status IN ('pending', 'processing')"),
        ),
    )


engine = create_async_engine(settings.pg_dsn, pool_size=10, max_overflow=10)
SessionLocal = async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)